### ISSUE TITLE
No attribute 'plot_assignment'

### ISSUE THREAD

**Issue by melyndaschreiber** [wmvanvliet/mne_microstates#1]
Hello Marjin, 

I recognize that this is a simple problem with a simple solution. There is an error when running your example on your readme.md. There is no plot_assignment module.  Not sure if it should say plot_segmentation or something else. 

Thanks for the module, 

Melynda

**Comment by wmvanvliet** [comment]
Hello Melynda,

thanks for telling me. You are right, that should have been `plot_segmentation`. I've updated the `README.md` file.

Glad that you found the module useful.
