### ISSUE TITLE
K-means clustering of the data at the selected GFP peaks

### ISSUE THREAD

**Issue by DraganaMana** [wmvanvliet/mne_microstates#3]
https://github.com/wmvanvliet/mne_microstates/blob/401447ca32971eda0b7c7bd744e754ab2b9abe0a/microstates.py#L92-L112

Hello Marijn, while working on a version of these codes for a project, I noticed a possible issue. 
As explained in literature "only the topographies at the GFP peaks are used as “original maps” in k-means clustering". However in the current code (microstates.py:89 to 99), the GFP peaks are found and chosen peaks are selected, but never used and the original data is being fed to the _mod_kmeans() function. My expectation is to give only the data at the chosen peaks to the k-means clustering. 

With @fraimondo we also checked other toolboxes such as https://github.com/Frederic-vW/eeg_microstates/blob/master/eeg_microstates.py (line 273) which also seems to use the same data without selecting only the GFP peaks time points (unless the data is saved in a new file). 
In the paper from Poulsen at al. 2018 on the EEGLab microstate toolbox, in section 3.3.2 they explain that: 
"EEG maps that represent peaks in the GFP time curve will be used for segmentation"
"In the case of Spontaneous data, for each subject, a selection of defined number of EEG maps at GFP peaks is randomly extracted and concatenated to one new dataset." 
"A new dataset will be created called MicroGFPpeakData (which is now listed under Datasets) that includes the EEG extracted and aggregated based on the GFP peaks."

Thus this indicates that the current code should indeed only use the data from the selected GFP peaks. 

Thanks a lot for the module, and your reply on this will be appreciated,
Dragana

**Comment by vferat** [comment]
I agree with @DraganaMana, only the `data[peaks]` should be used for the `_mod_kmeans`.
Also in [Cartool](https://sites.google.com/site/cartoolcommunity/), only the `data[peaks]` are used to compute the gev.

**Comment by wmvanvliet** [comment]
Thanks for raising the issue. The code is indeed wrong. I think I've fixed it in current master using this commit: https://github.com/wmvanvliet/mne_microstates/commit/a150e21d8d4981faf7c7cef85c2dc6d66d3c044f
