### ISSUE TITLE
Map computation

### ISSUE THREAD

**Issue by DominiqueMakowski** [wmvanvliet/mne_microstates#5]
Hi @wmvanvliet, I had a small question regarding these lines where you recompute the maps:

https://github.com/wmvanvliet/mne_microstates/blob/06b07d69ac44d3330a49008459910bac64d112c8/microstates.py#L173-L178

It seems like there are two ways, the one that you commented out, that is implemented in [eeg_microstates](https://github.com/Frederic-vW/eeg_microstates/blob/master/eeg_microstates.py#L583), and the other version. They produce different results in terms of intensity (blue is the commented out version):

![Figure_1](https://user-images.githubusercontent.com/8875533/89114046-f3523000-d4aa-11ea-8c9f-36bce38f68c0.png)

The difference persists after standardizing:

![Figure_2](https://user-images.githubusercontent.com/8875533/89114051-11b82b80-d4ab-11ea-9537-6a8c5daa02e4.png)

Thus, I was wondering why the uncommented version is to be favoured over the other one? Is it because it increases the range and the variability? Thanks a lot ☺️

**Comment by wmvanvliet** [comment]
We don't remember. Possibly I was following the implementation of a paper that didn't do the eigenvalue.

**Comment by DominiqueMakowski** [comment]
Okay no worries I'll try to dig a bit more and will let you know if I find anything! Thanks
