### ISSUE TITLE
Normalize activation by GFP?

### ISSUE THREAD

**Issue by DominiqueMakowski** [wmvanvliet/mne_microstates#6]
And another quick question, in this part where you assign the best matching map:

https://github.com/wmvanvliet/mne_microstates/blob/06b07d69ac44d3330a49008459910bac64d112c8/microstates.py#L160-L162

In [eeg_microstates](https://github.com/Frederic-vW/eeg_microstates/blob/bd202ee5e218c98c6515f3427bb9fc51a8bf9dce/eeg_microstates.py#L573), there is an additional step equivalent to:

```python
activation /= (n_channels * np.outer(gfp_values_at_peaks, np.std(maps, axis=1)))
```

 It seems to normalize the activation by the GFP (not sure, since I'm not sure what np.outer does). I tried with and without and it doesn't seem to affect the following segmentation extraction. Though I was just wondering if you had any hint about the purpose and utility of this line?

**Comment by wmvanvliet** [comment]
When the purpose is to pick the map with maximum activation, multiplying the activations for all maps with some constant doesn't do anything.

**Comment by DominiqueMakowski** [comment]
Thanks for confirming and reassuring me 😁
