### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by hoechenberger** [wmvanvliet/mne_microstates#7]
Hello, for inclusion of this package in the MNE Installer, we'd need a "proper" release on PyPI. If you have the time, it would be great if you could take a stab at this, @wmvanvliet!

**Comment by wmvanvliet** [comment]
Done!

```
pip install mne-microstates
```

**Comment by wmvanvliet** [comment]
Thanks @hoechenberger for putting up all my packages on conda-forge. It's much appreciated!
