### ISSUE TITLE
Suggestion: Change name of installed package to mne_microstates?

### ISSUE THREAD

**Issue by hoechenberger** [wmvanvliet/mne_microstates#8]
Hello,

after installing the package from PyPI, it can be imported via `import microstates`.

To be consistent with how other MNE-related packages are named, I was wondering if you would consider changing this to `mne_microstates`?

**Comment by wmvanvliet** [comment]
Done! Version `0.3` was minted.

**Comment by hoechenberger** [comment]
Amazing! 😍
