### ISSUE TITLE
Error plot segmentation

### ISSUE THREAD

**Issue by raniere-guimaraes** [wmvanvliet/mne_microstates#9]
Hi Marijn van Vliet,

Firstly, congratulation on your contribution through the code for microstates analysis. I tried to run in Jupyter-Notebook .edf file to find microstates, but following error appeared when plotting the segments:

ValueError: Unable to determine Axes to steal space for Colorbar. Either provide the *cax* argument to use as the Axes for the Colorbar, provide the *ax* argument to steal space from it, or add *mappable* to an Axes.

Could you tell me how to fix it?

Thanks

**Comment by raniere-guimaraes** [comment]
I managed to fix the error. I changed matplotlib version to 3.5.1

**Comment by wmvanvliet** [comment]
Glad to hear it!
